# Dockerfile-frontend

FROM node:20.5.0-alpine as build

WORKDIR /client
ENV PATH /client/node_modules/.bin:$PATH

COPY package.json /client/package.json
COPY package-lock.json /client/package-lock.json

RUN npm i --production
COPY . /client

RUN npm run build

CMD ["npm", "start"]
