FROM python:3.11.4-alpine

WORKDIR /usr/app/scrapy_spider

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install Twisted==22.10.0 

COPY . .

CMD scrapy crawl sreality