# server part

FROM python:3.11.4-alpine

WORKDIR /server

COPY requirements.txt /server/
RUN pip install --no-cache-dir -r requirements.txt

FROM postgres:latest
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=flats
COPY create_tables.sql /docker-entrypoint-initdb.d/create_tables.sql

COPY . /server

CMD ["python", "server.py"]
